version: '3'
 
services:
  simulator:
    build: ./Simulator
    command: >
      sh -c "npm install &&
             npm run watch"
    volumes:
      - ./Simulator:/usr/src/app/
    networks:
      - simulatorNet
    ports:  
      - "3000:3000"
    depends_on:
      - simDB
    environment:
      PGHOST: simDB
      PGUSER: sim
      PGPASSWORD: password
      PGDATABASE: simulator
    
  simDB:
    image: postgres
    environment:
      POSTGRES_USER: sim
      POSTGRES_DB: simulator
      POSTGRES_PASSWORD: password
    networks: 
      simulatorNet:
        aliases: 
          - "simDB"
    ports:
      - "5432:5432"
    volumes: 
      - ./Simulator/postgres/schemas/init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - ./Simulator/postgres/schemas/dummy_info.sql:/docker-entrypoint-initdb.d/20-init.sql

  postgressAdmin:
    image: dpage/pgadmin4
    depends_on:
      - simDB
    links: 
      - simDB
    networks:
      - simulatorNet
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "3001:80"

networks: 
  simulatorNet:
