version: '3'
 
services:

  prosumer:
    build: ./Prosumer
    container_name: "prosumer-web"
    command: >
      sh -c "npm install &&
             npm run watch"
    volumes:
      - ./Prosumer:/usr/src/app/
    networks:
      - prosumerNet
      - webNet
    ports:  
      - "3000:3000"
    depends_on:
      - promongo
    links:
      - promongo
    environment:
      MONGODB_USER: user
      MONGODB_PASS: pass

  simulator:
    build: ./Simulator
    container_name: "simulator-rest"
    command: >
      sh -c "npm install &&
             npm run watch"
    volumes:
      - ./Simulator:/usr/src/app/
    networks:
      - simulatorNet
      - webNet
    ports:  
      - "3100:3000"
    depends_on:
      - simDB
    environment:
      PGHOST: simDB
      PGUSER: sim
      PGPASSWORD: password
      PGDATABASE: simulator
    
  simDB:
    image: postgres
    container_name: "simulation-postgressdb"
    environment:
      POSTGRES_USER: sim
      POSTGRES_DB: simulator
      POSTGRES_PASSWORD: password
    networks: 
      simulatorNet:
        aliases: 
          - "simDB"
    ports:
      - "5432:5432"
    volumes: 
      - ./Simulator/postgres/schemas/init.sql:/docker-entrypoint-initdb.d/10-init.sql
      - ./Simulator/postgres/schemas/dummy_info.sql:/docker-entrypoint-initdb.d/20-init.sql

  postgressAdmin:
    image: dpage/pgadmin4
    container_name: "postgress-MyAdmin"
    depends_on:
      - simDB
    links: 
      - simDB
    networks:
      - simulatorNet
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "3001:80"

  promongo:
    image: mongo:latest
    container_name: "prosumer-mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./Prosumer/mongo/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

networks: 
  simulatorNet:
  prosumerNet:
  webNet:
