version: '3'
 
services:
  simulator:
    build: ./Simulator
    command: npm start
    volumes:
      - ./Simulator/src:/usr/src/app/src
    ports:
      - "3000:3000"
    depends_on:
      - simDB
    environment:
      DATABASE_URL: postgres://sim@postgres/simulator
    
  simDB
    image: postgres
    environment:
      POSTGRES_USER: sim
      POSTGRES_DB: simulator