version: '3'
 
services:
  simulator:
    build: ./Simulator
    command: >
      sh -c "npm install &&
             npm run watch"
    volumes:
      - ./Simulator:/usr/src/app/
    ports:
      - "3000:3000"
    depends_on:
      - simDB
    environment:
      DATABASE_URL: postgres://sim@postgres/simulator
    
  simDB:
    image: postgres
    environment:
      POSTGRES_USER: sim
      POSTGRES_DB: simulator